
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          type: trace


